src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Transaction_Limit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Limit</label>
        <referenceTo>Transaction_Limit__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Day__c</fullName>
        <label>Maximum Transactions Allowed per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Month__c</fullName>
        <label>Maximum Transactions Allowed per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionEntryTriggerHelper.cls
/**
*  Description     :  This is Transaction Entry Trigger handler Class
*
*  Created By      :  Rajat khatri
*
*  Created Date    :  04/14/2021
*
*  Revision Logs   :  V1.0 - Created - Rajat khatri 
*
**/
public with sharing class TransactionEntryTriggerHelper {
    /**
    * 
    *   @description    :   In this method we are chacking the Maximum Number of transaction for Particular Contact
    *
    *   @args           :   List of Transaction_Entry__c
    *
    *   @return         :   
    *
    *   @revision Log   :   V1.1 - Created  - 04/14/2021 - Rajat khatri
    * 
    **/
    public static void validationOnTransactionEntries(List<Transaction_Entry__c> newTxEntries){
        Map<Id,List<Transaction_Entry__c>> mapOfcontactIdsWithTxEntries = new Map<Id,List<Transaction_Entry__c>>();
        //storing the Contact id of TXEntry with list of transaction entries associated with it contact id
        for(Transaction_Entry__c txEntries : newTxEntries){
            if(!mapOfcontactIdsWithTxEntries.containsKey(txEntries.Contact__c)){
                mapOfcontactIdsWithTxEntries.put(txEntries.Contact__c, new List<Transaction_Entry__c>());
            }
                mapOfcontactIdsWithTxEntries.get(txEntries.Contact__c).add(txEntries);
        }
        //checking the size of map
        if(mapOfcontactIdsWithTxEntries.size() > 0){
            //stroring the Contact id with contact
            Map<Id,Contact> mapContactIdWithContact = new Map<Id,Contact>();
            //populating map with ids and contacts
            for(Contact con :[SELECT Id, Transaction_Limit__r.Maximum_Transactions_Allowed_per_Day__c, Transaction_Limit__r.Maximum_Transactions_Allowed_per_Month__c, Transaction_Limit__r.Maximum_Debit_Allowed_per_Day__c, Transaction_Limit__r.Maximum_Debit_Allowed_per_Month__c FROM Contact WHERE Id IN:mapOfcontactIdsWithTxEntries.keySet()]){
                if(!mapCOntactIdWithContact.containsKey(con.Id)){
                    mapCOntactIdWithContact.put(con.Id, con);
                }
            }
            //storing Contact id with String of count of TxEntries and total Debit amount for today
            Map<Id,String> mapOfContactIdWithTodayTxEntriesCount = new Map<Id,String>();
            //applying Aggregate query and populating the map
            for(AggregateResult ar : [SELECT COUNT(Id) totalTxEntry, SUM(Amount__c) amount,Contact__c,Type__c FROM Transaction_Entry__c WHERE Transaction_Date__c = TODAY AND Contact__c IN:mapContactIdWithContact.keySet() Group By Type__c,Contact__c]){
                if(!mapOfContactIdWithTodayTxEntriesCount.containsKey((Id)ar.get('Contact__c'))){
                    mapOfContactIdWithTodayTxEntriesCount.put((Id)ar.get('Contact__c'), String.valueOf(ar.get('totalTxEntry')) + ',' + String.valueOf((ar.get('Type__c') == 'Debit' ? (Double)ar.get('amount') : 0)));
                }
                else{
                    Integer todayTxEntries = Integer.valueOf(mapOfContactIdWithTodayTxEntriesCount.get((Id)ar.get('Contact__c')).split( ',' )[0]) + (Integer)ar.get('totalTxEntry');
                    Double todayDebitAmount = Double.valueOf(mapOfContactIdWithTodayTxEntriesCount.get((Id)ar.get('Contact__c')).split( ',' )[1]) + (ar.get('Type__c') == 'Debit' ? (Double)ar.get('amount') : 0);
                    mapOfContactIdWithTodayTxEntriesCount.put((Id)ar.get('Contact__c'), todayTxEntries + ',' + todayDebitAmount);
                }
            }
            System.debug('today: ' + mapOfContactIdWithTodayTxEntriesCount);
            //storing Contact id with String of count of TxEntries and total Debit amount for today
            Map<Id,String> mapOfContactIdWithMonthTxEntriesCount = new Map<Id,String>();
            //applying Aggregate query and populating the map
            for(AggregateResult ar : [SELECT COUNT(Id) totalTxEntry, SUM(Amount__c) amount,Contact__c,Type__c FROM Transaction_Entry__c WHERE CALENDAR_MONTH(Transaction_Date__c) =:(Integer)System.Today().Month() AND CALENDAR_YEAR(Transaction_Date__c) =:(Integer)System.Today().Year() AND Contact__c IN:mapContactIdWithContact.keySet() Group By Type__c,Contact__c]){
                if(!mapOfContactIdWithMonthTxEntriesCount.containsKey((Id)ar.get('Contact__c'))){
                    mapOfContactIdWithMonthTxEntriesCount.put((Id)ar.get('Contact__c'), String.valueOf(ar.get('totalTxEntry')) + ',' + String.valueOf((ar.get('Type__c') == 'Debit' ? (Double)ar.get('amount') : 0)));
                }
                else{
                    Integer monthTxEntries = Integer.valueOf(mapOfContactIdWithMonthTxEntriesCount.get((Id)ar.get('Contact__c')).split( ',' )[0]) + (Integer)ar.get('totalTxEntry');
                    Double monthDebitAmount = Double.valueOf(mapOfContactIdWithMonthTxEntriesCount.get((Id)ar.get('Contact__c')).split( ',' )[1]) + (ar.get('Type__c') == 'Debit' ? (Double)ar.get('amount') : 0);
                    mapOfContactIdWithMonthTxEntriesCount.put((Id)ar.get('Contact__c'), monthTxEntries + ',' + monthDebitAmount);
                }
            }
            System.debug('This Month: ' + mapOfContactIdWithMonthTxEntriesCount);
            for(Id conId : mapOfcontactIdsWithTxEntries.keySet()){
                for(Transaction_Entry__c txEntry : mapOfcontactIdsWithTxEntries.get(conId)){
                    if(mapOfContactIdWithTodayTxEntriesCount.get(txEntry.Contact__c) != null){
                        //isNotBlank(String.valueOf(mapOfContactIdWithTodayTxEntriesCount.get(txEntry.Contact__c)))
                        //checking the today transaction limits
                        if(Integer.valueOf(mapOfContactIdWithTodayTxEntriesCount.get(txEntry.Contact__c).split( ',' )[0]) >= mapContactIdWithContact.get(txEntry.Contact__c).Transaction_Limit__r.Maximum_Transactions_Allowed_per_Day__c){
                        	txEntry.addError('You can not credit/debit from your account, your today'+'\''+'s limit is exceeded.');
                    	}
                        //checking the today debit amount limit
                    	if(Integer.valueOf(mapOfContactIdWithTodayTxEntriesCount.get(txEntry.Contact__c).split( ',' )[1]) >= mapContactIdWithContact.get(txEntry.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_per_Day__c){
                        	txEntry.addError('Amount from your account can not be debited, your Amount Debit Limit for today' +'\''+'s is exceeded.');
                    	}
                    }
                    if(mapOfContactIdWithMonthTxEntriesCount.get(txEntry.Contact__c) != null){
                        if(Integer.valueOf(mapOfContactIdWithMonthTxEntriesCount.get(txEntry.Contact__c).split( ',' )[0]) >= mapContactIdWithContact.get(txEntry.Contact__c).Transaction_Limit__r.Maximum_Transactions_Allowed_per_Month__c){
                        	txEntry.addError('You can not credit/debit from your account, your Month'+'\''+'s limit is exceeded.');
                    	}
                    	if(Integer.valueOf(mapOfContactIdWithMonthTxEntriesCount.get(txEntry.Contact__c).split( ',' )[1]) >= mapContactIdWithContact.get(txEntry.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_per_Month__c){
                        	txEntry.addError('Amount from your account can not be debited, your Amount Debit Limit for Month' +'\''+'s is exceeded.');
                    	}
                    }  
                }
            }			
        }
    }
 }