src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Limit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Limit</label>
        <referenceTo>Transaction_Limit__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Transaction__c</fullName>
        <label>Maximum Debit Allowed per Transaction</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Day__c</fullName>
        <label>Maximum Transactions Allowed per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Month__c</fullName>
        <label>Maximum Transactions Allowed per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TransactionEntryTriggerHelper.cls
@isTest//SELECT Id,Name FROM Contact WHERE FirstName = 'Test' ORDER BY Name ASC
public with sharing class Test_TransactionEntryTriggerHelper {
    @testSetup
    static void setup(){
		Test.setMock(HttpCalloutMock.class, new Test_qrCodeGeneretorMock());
        
        Transaction_Limit__c TxLimit1 = new Transaction_Limit__c();
        TxLimit1.Name = 'Test TxLimit1';
        TxLimit1.Maximum_Debit_Allowed_per_Day__c = 100000;
        TxLimit1.Maximum_Debit_Allowed_per_Month__c = 10000000;
        TxLimit1.Maximum_Transactions_Allowed_per_Day__c = 300;
        TxLimit1.Maximum_Transactions_Allowed_per_Month__c = 700;
        TxLimit1.Maximum_Debit_Allowed_per_Transaction__c = 10000;
        insert TxLimit1;
        
        Transaction_Limit__c TxLimit2 = new Transaction_Limit__c();
        TxLimit2.Name = 'Test TxLimit2';
        TxLimit2.Maximum_Debit_Allowed_per_Day__c = 1000;
        TxLimit2.Maximum_Debit_Allowed_per_Month__c = 10000;
        TxLimit2.Maximum_Transactions_Allowed_per_Day__c = 3;
        TxLimit2.Maximum_Transactions_Allowed_per_Month__c = 7;
        TxLimit2.Maximum_Debit_Allowed_per_Transaction__c = 1000;
        insert TxLimit2;

        
        Contact con = new Contact();
        con.LastName = 'Test Contact';
        con.Email = 'tessttContact@zyx.com';
        con.Status__c = 'Active';
        con.Transaction_Limit__c = TxLimit1.Id;
        insert con;
        
        Contact con1 = new Contact();
        con1.LastName = 'Test Contact1';
        con1.Email = 'tessttContact1@zyx.com';
        con1.Status__c = 'Active';
        con1.Transaction_Limit__c = TxLimit2.Id;
        insert con1;

    }

    static testMethod void test_validationOnTransactionEntries(){
        Contact con = [SELECT Id,Name, Available_Balance__c FROM Contact WHERE Email = 'tessttContact@zyx.com'];
        Contact con1 = [SELECT Id,Name, Available_Balance__c FROM Contact WHERE Email = 'tessttContact1@zyx.com'];
        
        Test.startTest();
        
        List<Transaction_Entry__c> txEntries1 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 100; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10000;
            TxEntry.Status__c = 'Completed';
            TxEntry.Type__c = 'Credit';
            TxEntry.Contact__c = con.Id;
            txEntries1.add(txEntry);
        }
        insert txEntries1;
        
        List<Transaction_Entry__c> txEntries2 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 100; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10;
            TxEntry.Status__c = 'Completed';
            TxEntry.Type__c = 'Debit';
            TxEntry.Contact__c = con.Id;
            txEntries2.add(txEntry);
        }
        insert txEntries2;
        
        List<Transaction_Entry__c> txEntries3 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 10; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10;
            TxEntry.Status__c = 'Pending';
            TxEntry.Type__c = 'Debit';
            TxEntry.Contact__c = con.Id;
            txEntries3.add(txEntry);
        }
        insert txEntries3;
        
        List<Transaction_Entry__c> txEntries4 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 10; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10;
            TxEntry.Status__c = 'Cancelled.';
            TxEntry.Type__c = 'Debit';
            TxEntry.Contact__c = con.Id;
            txEntries4.add(txEntry);
        }
        insert txEntries4;
        
        List<Transaction_Entry__c> txEntries5 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 10; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10;
            TxEntry.Status__c = 'Pending';
            TxEntry.Type__c = 'Credit';
            TxEntry.Contact__c = con.Id;
            txEntries5.add(txEntry);
        }
        insert txEntries5;
        
        List<Transaction_Entry__c> txEntries6 = new List<Transaction_Entry__c>();
        for(Integer i = 0; i < 10; i++){
            Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10;
            TxEntry.Status__c = 'Cancelled.';
            TxEntry.Type__c = 'Credit';
            TxEntry.Contact__c = con.Id;
            txEntries6.add(txEntry);
        }
        insert txEntries6;
        
       
        List<Transaction_Entry__c> insertedTxEntries = [SELECT Id,Name FROM Transaction_Entry__c WHERE Contact__c =:con.Id];
        System.assertEquals(240,insertedTxEntries.size());
        
        Transaction_Entry__c txEntry = new Transaction_Entry__c();
            TxEntry.Transaction_Date__c = Date.today();
            TxEntry.Amount__c = 10000;
            TxEntry.Status__c = 'Completed';
            TxEntry.Type__c = 'Credit';
            TxEntry.Contact__c = con1.Id;
            insert txEntry;
        
        try{
            List<Transaction_Entry__c> txEntries7 = new List<Transaction_Entry__c>();
            txEntries7.add(new Transaction_Entry__c(Transaction_Date__c = Date.today(),Amount__c = 1000,Status__c = 'Completed',Type__c = 'Credit',Contact__c = con1.Id));
            txEntries7.add(new Transaction_Entry__c(Transaction_Date__c = Date.today(),Amount__c = 1000,Status__c = 'Completed',Type__c = 'Credit',Contact__c = con1.Id));
            txEntries7.add(new Transaction_Entry__c(Transaction_Date__c = Date.today(),Amount__c = 1000,Status__c = 'Completed',Type__c = 'Credit',Contact__c = con1.Id));
            insert txEntries7;
            
        }
        catch(Exception ex){
            System.assertEquals(true, ex.getMessage().contains('You can not credit/debit from your account, your today'+'\''+'s limit is exceeded.'));
        }
        
        Test.stopTest();        
    }
}