src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TestFactory.cls
@isTest
public class Test_TestFactory {

    public static testMethod void test_Factory(){
        System.debug('*********ACCOUNT**********');
        Account a = (Account)TestFactory.createSObject(new Account());
		insert a;
		System.debug(a);
	/*
        System.debug('*********ACCOUNT with Default Class**********');
        Account a2 = (Account)TestFactory.createSObject(new Account(),'TestFactoryDefaults.MyAccountDefaults');
		insert a2;
		System.debug(a2);

        System.debug('*********ACCOUNT WITH DO INSERT**********');
        Account a1 = (Account)TestFactory.createSObject(new Account(),true);
		System.debug(a1);

        System.debug('*********CONTACT**********');
        Contact con = (Contact)TestFactory.createSObject(new Contact(AccountId = a.Id));
        System.debug(con);
        insert con;

        System.debug('*********CONTACT WITH DO INSERT**********');
        Contact con1 = (Contact)TestFactory.createSObject(new Contact(AccountId = a.Id),true);
        System.debug(con1);

        System.debug('**********OPPORTUNITY*********');
        Opportunity opp = (Opportunity)TestFactory.createSObject(New Opportunity());
        Insert opp;
        System.debug(opp);
        
        System.debug('********ACCOUNT LIST***********');
		Account[] aList = (Account[])TestFactory.createSObjectList(new Account(), 5);
        
        System.debug('********ACCOUNT LIST***********');
		Account[] aList1 = (Account[])TestFactory.createSObjectList(new Account(), 5, 'TestFactoryDefaults.MyAccountDefaults',true);
        for(Account acc : aList1){
            System.debug(acc);
        }
        
        System.debug('*********CONTACT**********');
        Contact con = (Contact)TestFactory.createSObject(new Contact());
        System.debug(con);
        insert con;
        
        System.debug('*********TRANSACTION ENTRY**********');
        Transaction_Entry__c txEntry = (Transaction_Entry__c)TestFactory.createSObject(new Transaction_Entry__c(Contact__c = con.id));
        System.debug(txEntry);
        Transaction_Entry__c[] txEntryList = (Transaction_Entry__c[])TestFactory.createSObjectList(new Transaction_Entry__c(Contact__c = con.id),5);
        for(Transaction_Entry__c tx :txEntryList){System.debug(tx);}*/
    } 
    
}