src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MiniStatmentComponentControler.cls
/**
*  Description     :  This is the Apex class for Backend functioning for LWC component for Mini Statment
*
*  Created By      :  Rajat khatri
*
*  Created Date    :  04/19/2021
*
*  Revision Logs   :  V1.0 - Created - Rajat khatri 
*
**/
public with sharing class MiniStatmentComponentControler {
    /**
    * 
    *   @description    :   In this method we are fetching transaction entries based on the passed record Id.
    *
    *   @args           :   String
    *
    *   @return         :   List<Transaction_Entry__c>
    *
    *   @revision Log   :   V1.1 - Created  - 04/19/2021 - Rajat khatri
    * 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Transaction_Entry__c> getTransactionEntries(String recId, Integer selectedOption){
        if(String.isNotBlank(recId) || selectedOption != null){
            List<Transaction_Entry__c> trnEntries  = [SELECT Id,Name,Amount__C,Status__c,Type__c FROM Transaction_Entry__c WHERE
                                                      Contact__c=:recId LIMIT :selectedOption];
            System.debug(trnEntries);
            if(trnEntries.size() > 0){
                return trnEntries;
            }
        }
        return null; 
    }
}